#!/usr/bin/perl -w

#    rapprove - approve reviewed rbackup image
#
#    Copyright (C) 2006 Anthony de Boer
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License as
#    published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;

my $dir = $ARGV[0];
if (defined($dir) && substr($dir, 0, 1) ne '-') {
	chdir($dir) || die "Cannot cd $dir: $!\n";
	shift @ARGV;
	}

if (-d 'old') {
	chdir('old') || die "Cannot cd into \'old\': $!\n";
	}

rename("current", "previous") || die "Cannot rename symlink: $!\n";

